"""add sub accounts to users

Revision ID: 02c404cc040a
Revises: 1cfb2d0615cf
Create Date: 2026-10-03 00:28:13.750336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02c404cc040a'
down_revision: Union[str, Sequence[str], None] = '1cfb2d0615cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_player_account_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('add_main', 'add_sub', 'remove', 'set_main', 'set_sub')", name='ck_user_player_account_events_action'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_player_account_events_tag', 'user_player_account_events', ['tag'], unique=False)
    op.create_index('ix_user_player_account_events_user_id_created_at', 'user_player_account_events', ['user_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('sub_accounts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('sub_accounts_limit', sa.Integer(), server_default='1', nullable=False))
    op.create_index('idx_users_main_account', 'users', ['main_account'], unique=False)
    op.create_index('idx_users_sub_accounts', 'users', ['sub_accounts'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_users_sub_accounts_limit_range',
        'users',
        'sub_accounts_limit >= 1 AND sub_accounts_limit <= 9',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_users_sub_accounts_limit_range', 'users', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_sub_accounts', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_main_account', table_name='users')
    op.drop_column('users', 'sub_accounts_limit')
    op.drop_column('users', 'sub_accounts')
    op.drop_index('ix_user_player_account_events_user_id_created_at', table_name='user_player_account_events')
    op.drop_index('ix_user_player_account_events_tag', table_name='user_player_account_events')
    op.drop_table('user_player_account_events')
    # ### end Alembic commands ###
