"""Add history privacy flags to players

Revision ID: 0865fccfe34c
Revises: 6245573c200a
Create Date: 2025-09-19 06:31:16.354415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0865fccfe34c'
down_revision: Union[str, Sequence[str], None] = '6245573c200a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hide_name_history', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('players', sa.Column('hide_club_history', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'hide_club_history')
    op.drop_column('players', 'hide_name_history')
    # ### end Alembic commands ###
