"""Add ranked stats summary tables 2

Revision ID: 129bf868e740
Revises: 6159124a07f5
Create Date: 2025-08-09 04:00:04.582200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129bf868e740'
down_revision: Union[str, Sequence[str], None] = '6159124a07f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranked_stats_brawler', 'rank_tier',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='rank_tier::integer')
    op.alter_column('ranked_stats_composition', 'rank_tier',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='rank_tier::integer')
    op.alter_column('ranked_stats_synergy', 'rank_tier',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='rank_tier::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranked_stats_synergy', 'rank_tier',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ranked_stats_composition', 'rank_tier',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ranked_stats_brawler', 'rank_tier',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
