"""Add last_advance_mission_date

Revision ID: 1561518cc9d0
Revises: f49acb4e4ca1
Create Date: 2026-06-21 00:49:19.138004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1561518cc9d0'
down_revision: Union[str, Sequence[str], None] = 'f49acb4e4ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_advance_mission_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_advance_mission_date')
    # ### end Alembic commands ###
