"""Add hyper_charges, buffies to players and logs, and ownership stats to skins

Revision ID: 1bb9eaf147b5
Revises: e5e45985817b
Create Date: 2026-02-27 02:03:57.154225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb9eaf147b5'
down_revision: Union[str, Sequence[str], None] = 'e5e45985817b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accessories_brawler_id_fkey'), 'accessories', type_='foreignkey')
    op.create_foreign_key(None, 'accessories', 'brawlers', ['brawler_id'], ['id'], ondelete='CASCADE')
    op.add_column('player_logs', sa.Column('hyper_charges', sa.Integer(), server_default='0', nullable=False))
    op.add_column('player_logs', sa.Column('buffies', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('hyper_charges', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('buffies', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skins', sa.Column('ownership_rate', sa.Float(), nullable=True))
    op.add_column('skins', sa.Column('equip_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'equip_rate')
    op.drop_column('skins', 'ownership_rate')
    op.drop_column('players', 'buffies')
    op.drop_column('players', 'hyper_charges')
    op.drop_column('player_logs', 'buffies')
    op.drop_column('player_logs', 'hyper_charges')
    op.drop_constraint(None, 'accessories', type_='foreignkey')
    op.create_foreign_key(op.f('accessories_brawler_id_fkey'), 'accessories', 'brawlers', ['brawler_id'], ['id'])
    # ### end Alembic commands ###
