"""create faqs table

Revision ID: 2ec0aa4c1aa0
Revises: 1b9e1fc67bee
Create Date: 2026-02-25 01:37:40.046302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec0aa4c1aa0'
down_revision: Union[str, Sequence[str], None] = '1b9e1fc67bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category_ja', sa.Text(), nullable=False),
    sa.Column('category_en', sa.Text(), nullable=False),
    sa.Column('title_ja', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('body_ja', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    # ### end Alembic commands ###
