"""Add battle card tables

Revision ID: 317f0fa0bc24
Revises: 85ad81caee12
Create Date: 2026-03-11 05:39:47.291032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317f0fa0bc24'
down_revision: Union[str, Sequence[str], None] = '85ad81caee12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('ja', sa.Text(), nullable=True),
    sa.Column('equip_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brawler_id', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('equip_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brawler_id'], ['brawlers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brawler_id', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('ja', sa.Text(), nullable=True),
    sa.Column('equip_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brawler_id'], ['brawlers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles')
    op.drop_table('pins')
    op.drop_table('frames')
    # ### end Alembic commands ###
