"""add buffies

Revision ID: 3d8065a5bbc0
Revises: c55c2d5b7b0b
Create Date: 2026-09-29 22:47:38.821804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8065a5bbc0'
down_revision: Union[str, Sequence[str], None] = 'c55c2d5b7b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brawler_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('ja', sa.Text(), nullable=True),
    sa.Column('is_invalid', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['brawler_id'], ['brawlers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buffies_brawler', 'buffies', ['brawler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buffies_brawler', table_name='buffies')
    op.drop_table('buffies')
    # ### end Alembic commands ###
