"""create_brawler_accessory_stats_table

Revision ID: 4132e8f5ea03
Revises: abc5a8a5d057
Create Date: 2026-02-11 17:33:26.243842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4132e8f5ea03'
down_revision: Union[str, Sequence[str], None] = 'abc5a8a5d057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brawler_accessory_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brawler_id', sa.Integer(), nullable=False),
    sa.Column('gadget_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('star_power_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('gear_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['brawler_id'], ['brawlers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'brawler_id', name='brawler_accessory_stats_pkey')
    )
    op.create_index('idx_brawler_accessory_stats_brawler_date', 'brawler_accessory_stats', ['brawler_id', sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_brawler_accessory_stats_brawler_date', table_name='brawler_accessory_stats')
    op.drop_table('brawler_accessory_stats')
    # ### end Alembic commands ###
