"""add_board_notifications_table_and_user_notification_settings

Revision ID: 4aa6c2581dbe
Revises: 1561518cc9d0
Create Date: 2026-06-21 19:52:19.234086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa6c2581dbe'
down_revision: Union[str, Sequence[str], None] = '1561518cc9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('post_vote_id', sa.Integer(), nullable=True),
    sa.Column('reaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_vote_id'], ['post_votes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_board_notifications_message_id', 'board_notifications', ['message_id'], unique=False)
    op.create_index('idx_board_notifications_post_id', 'board_notifications', ['post_id'], unique=False)
    op.create_index('idx_board_notifications_recipient_created_at', 'board_notifications', ['recipient_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_board_notifications_recipient_type_message', 'board_notifications', ['recipient_user_id', 'notification_type', 'message_id'], unique=False)
    op.create_index('idx_board_notifications_recipient_type_post', 'board_notifications', ['recipient_user_id', 'notification_type', 'post_id'], unique=False)
    op.add_column('users', sa.Column('notification_badge_enabled', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('notification_post_like_enabled', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('notification_own_post_message_enabled', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('notification_participated_thread_message_enabled', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('notification_message_reaction_enabled', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('notifications_last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_last_read_at')
    op.drop_column('users', 'notification_message_reaction_enabled')
    op.drop_column('users', 'notification_participated_thread_message_enabled')
    op.drop_column('users', 'notification_own_post_message_enabled')
    op.drop_column('users', 'notification_post_like_enabled')
    op.drop_column('users', 'notification_badge_enabled')
    op.drop_index('idx_board_notifications_recipient_type_post', table_name='board_notifications')
    op.drop_index('idx_board_notifications_recipient_type_message', table_name='board_notifications')
    op.drop_index('idx_board_notifications_recipient_created_at', table_name='board_notifications')
    op.drop_index('idx_board_notifications_post_id', table_name='board_notifications')
    op.drop_index('idx_board_notifications_message_id', table_name='board_notifications')
    op.drop_table('board_notifications')
    # ### end Alembic commands ###
