"""Add board stats columns to usage_stats

Revision ID: 5635ab863fb7
Revises: d581d4a82eaa
Create Date: 2025-07-27 17:25:40.661486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5635ab863fb7'
down_revision: Union[str, Sequence[str], None] = 'd581d4a82eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('posts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_stats', sa.Column('team_posts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_stats', sa.Column('friend_posts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_stats', sa.Column('club_posts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_stats', sa.Column('messages', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usage_stats', sa.Column('reactions', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_stats', 'reactions')
    op.drop_column('usage_stats', 'messages')
    op.drop_column('usage_stats', 'club_posts')
    op.drop_column('usage_stats', 'friend_posts')
    op.drop_column('usage_stats', 'team_posts')
    op.drop_column('usage_stats', 'posts')
    # ### end Alembic commands ###
