"""Add ranked stats summary tables

Revision ID: 6159124a07f5
Revises: 8f2bddf3b050
Create Date: 2025-08-09 03:35:19.542510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6159124a07f5'
down_revision: Union[str, Sequence[str], None] = '8f2bddf3b050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranked_stats_brawler',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('map', sa.Text(), nullable=False),
    sa.Column('rank_tier', sa.Text(), nullable=False),
    sa.Column('brawler_id', sa.Integer(), nullable=False),
    sa.Column('total_games_in_condition', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('use_rate', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('star_player_count', sa.Integer(), nullable=False),
    sa.Column('star_player_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'mode', 'map', 'rank_tier', 'brawler_id', name='ranked_stats_brawler_pkey')
    )
    op.create_table('ranked_stats_composition',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('map', sa.Text(), nullable=False),
    sa.Column('rank_tier', sa.Text(), nullable=False),
    sa.Column('brawler_id_1', sa.Integer(), nullable=False),
    sa.Column('brawler_id_2', sa.Integer(), nullable=False),
    sa.Column('brawler_id_3', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('brawler_id_1 < brawler_id_2 AND brawler_id_2 < brawler_id_3', name='ck_composition_brawler_order'),
    sa.PrimaryKeyConstraint('date', 'mode', 'map', 'rank_tier', 'brawler_id_1', 'brawler_id_2', 'brawler_id_3', name='ranked_stats_composition_pkey')
    )
    op.create_table('ranked_stats_synergy',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('map', sa.Text(), nullable=False),
    sa.Column('rank_tier', sa.Text(), nullable=False),
    sa.Column('brawler_id_1', sa.Integer(), nullable=False),
    sa.Column('brawler_id_2', sa.Integer(), nullable=False),
    sa.Column('synergy_games_played', sa.Integer(), nullable=False),
    sa.Column('synergy_wins', sa.Integer(), nullable=False),
    sa.Column('synergy_win_rate', sa.Float(), nullable=False),
    sa.Column('counter_games_played', sa.Integer(), nullable=False),
    sa.Column('counter_wins', sa.Integer(), nullable=False),
    sa.Column('counter_win_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('brawler_id_1 < brawler_id_2', name='ck_synergy_brawler_order'),
    sa.PrimaryKeyConstraint('date', 'mode', 'map', 'rank_tier', 'brawler_id_1', 'brawler_id_2', name='ranked_stats_synergy_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranked_stats_synergy')
    op.drop_table('ranked_stats_composition')
    op.drop_table('ranked_stats_brawler')
    # ### end Alembic commands ###
