"""Add host_anonymous_id to posts table

Revision ID: 6245573c200a
Revises: 9ac0db547f26
Create Date: 2025-08-29 18:22:35.015740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '6245573c200a'
down_revision: Union[str, Sequence[str], None] = '9ac0db547f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('host_anonymous_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    
    # 既存の未ログイン投稿を取得するために、一時的にテーブルオブジェクトを定義
    posts_table = sa.table('posts',
        sa.column('id', sa.Integer),
        sa.column('host_id', sa.Integer),
        sa.column('host_ip', sa.dialects.postgresql.INET),
        sa.column('host_anonymous_id', sa.Text)
    )
    
    # データベースに接続
    bind = op.get_bind()
    
    # host_idがNULLの投稿をIPアドレスでグループ化して取得
    # DISTINCT ON (host_ip) を使って、各IPアドレスから1行だけ取得
    results = bind.execute(sa.text("SELECT DISTINCT ON (host_ip) host_ip FROM posts WHERE host_id IS NULL AND host_ip IS NOT NULL")).fetchall()

    # 各IPアドレスに対して、一意の匿名IDを生成し、該当する全投稿を更新
    for row in results:
        ip_address = str(row[0])
        # IPアドレスから一貫性のあるUUID (バージョン5) を生成
        anonymous_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, ip_address))
        
        # このIPアドレスを持つすべての未ログイン投稿のhost_anonymous_idを更新
        bind.execute(
            posts_table.update().
            where(posts_table.c.host_ip == ip_address).
            where(posts_table.c.host_id.is_(None)).
            values(host_anonymous_id=anonymous_id)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'host_anonymous_id')
    # ### end Alembic commands ###
