"""Fully define players table and add indexes

Revision ID: 62ea0605a119
Revises: 5635ab863fb7
Create Date: 2025-07-29 19:51:10.692726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62ea0605a119'
down_revision: Union[str, Sequence[str], None] = '5635ab863fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'average_highest_trophies',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('players', 'average_power',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('idx_gin_players_name', 'players', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_gin_players_previous_names', 'players', ['previous_names'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gin_players_previous_names', table_name='players', postgresql_using='gin')
    op.drop_index('idx_gin_players_name', table_name='players', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.alter_column('players', 'average_power',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('players', 'average_highest_trophies',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
