"""add general posts to usage stats

Revision ID: 66e42e62affd
Revises: f31a9b6c4d2e
Create Date: 2026-03-28 16:06:25.486181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e42e62affd'
down_revision: Union[str, Sequence[str], None] = 'f31a9b6c4d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('general_posts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_stats', 'general_posts')
    # ### end Alembic commands ###
