"""Add battle_card_stars column to players

Revision ID: 75d05742b70d
Revises: 317f0fa0bc24
Create Date: 2026-03-11 07:42:34.340105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d05742b70d'
down_revision: Union[str, Sequence[str], None] = '317f0fa0bc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('battle_card_stars', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'battle_card_stars')
    # ### end Alembic commands ###
