"""Add battle card columns to players table

Revision ID: 85ad81caee12
Revises: fed9f681d93d
Create Date: 2026-03-10 11:25:39.529628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ad81caee12'
down_revision: Union[str, Sequence[str], None] = 'fed9f681d93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('favorite_skin', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('first_profile_avatar', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('second_profile_avatar', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('battle_card_emote', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('battle_card_title', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('battle_card_frame', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('milestone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'milestone')
    op.drop_column('players', 'battle_card_frame')
    op.drop_column('players', 'battle_card_title')
    op.drop_column('players', 'battle_card_emote')
    op.drop_column('players', 'second_profile_avatar')
    op.drop_column('players', 'first_profile_avatar')
    op.drop_column('players', 'favorite_skin')
    # ### end Alembic commands ###
