"""Add category to Announcement

Revision ID: 8d5d4f296310
Revises: c3f9a1d2e7f0
Create Date: 2026-05-06 16:45:28.010143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5d4f296310'
down_revision: Union[str, Sequence[str], None] = 'c3f9a1d2e7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'category')
    # ### end Alembic commands ###
