"""Sync all models with DB schema

Revision ID: 8f2bddf3b050
Revises: c0d2328c2768
Create Date: 2025-08-08 18:08:26.157978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2bddf3b050'
down_revision: Union[str, Sequence[str], None] = 'c0d2328c2768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_logs', 'average_highest_trophies',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('player_logs', 'average_power',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_logs', 'average_power',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('player_logs', 'average_highest_trophies',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
