"""Add user_blocks table

Revision ID: 9ac0db547f26
Revises: fde5caada801
Create Date: 2025-08-28 12:48:17.847173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac0db547f26'
down_revision: Union[str, Sequence[str], None] = 'fde5caada801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_user_id', sa.Integer(), nullable=True),
    sa.Column('blocker_anonymous_id', sa.Text(), nullable=True),
    sa.Column('blocked_user_id', sa.Integer(), nullable=True),
    sa.Column('blocked_anonymous_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(blocked_user_id, blocked_anonymous_id) = 1', name='ck_user_blocks_blocked_one_not_null'),
    sa.CheckConstraint('num_nonnulls(blocker_user_id, blocker_anonymous_id) = 1', name='ck_user_blocks_blocker_one_not_null'),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_anonymous_id', 'blocked_anonymous_id', name='uq_user_blocks_anonymous_to_anonymous'),
    sa.UniqueConstraint('blocker_anonymous_id', 'blocked_user_id', name='uq_user_blocks_anonymous_to_user'),
    sa.UniqueConstraint('blocker_user_id', 'blocked_anonymous_id', name='uq_user_blocks_user_to_anonymous'),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name='uq_user_blocks_user_to_user')
    )
    op.create_index('idx_user_blocks_blocker', 'user_blocks', ['blocker_user_id', 'blocker_anonymous_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_blocks_blocker', table_name='user_blocks')
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
