"""add club bookmark/history columns to users

Revision ID: a9e19646d2af
Revises: 5518e7243cc6
Create Date: 2026-03-31 11:53:12.481211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e19646d2af'
down_revision: Union[str, Sequence[str], None] = '5518e7243cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saved_clubs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('viewed_clubs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('saved_clubs_limit', sa.Integer(), server_default='3', nullable=False))
    op.add_column('users', sa.Column('viewed_clubs_limit', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'viewed_clubs_limit')
    op.drop_column('users', 'saved_clubs_limit')
    op.drop_column('users', 'viewed_clubs')
    op.drop_column('users', 'saved_clubs')
    # ### end Alembic commands ###
