"""Update previous_names index to use jsonb_path_ops

Revision ID: c0d2328c2768
Revises: 62ea0605a119
Create Date: 2025-07-30 21:34:14.344465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0d2328c2768'
down_revision: Union[str, Sequence[str], None] = '62ea0605a119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_gin_players_previous_names'), table_name='players', postgresql_using='gin')
    op.create_index('idx_gin_players_previous_names_path_ops', 'players', ['previous_names'], unique=False, postgresql_using='gin', postgresql_ops={'previous_names': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gin_players_previous_names_path_ops', table_name='players', postgresql_using='gin', postgresql_ops={'previous_names': 'jsonb_path_ops'})
    op.create_index(op.f('idx_gin_players_previous_names'), 'players', ['previous_names'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
