"""add last_updated_at and composite index

Revision ID: c20ba600cc45
Revises: c8d4e5f6a7b2
Create Date: 2026-02-26 05:49:59.886548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20ba600cc45'
down_revision: Union[str, Sequence[str], None] = 'c8d4e5f6a7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_players_level_updated_at', 'players', ['level', 'last_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_players_level_updated_at', table_name='players')
    op.drop_column('players', 'last_updated_at')
    # ### end Alembic commands ###
