"""add main account reward claims

Revision ID: c55c2d5b7b0b
Revises: 630e26b8a8c3
Create Date: 2026-09-29 13:11:47.690698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55c2d5b7b0b'
down_revision: Union[str, Sequence[str], None] = '630e26b8a8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_account_reward_claims',
    sa.Column('main_account', sa.Text(), nullable=False),
    sa.Column('reward_key', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('count >= 0', name='ck_main_account_reward_claims_count_nonnegative'),
    sa.ForeignKeyConstraint(['last_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('main_account', 'reward_key', 'period', name='pk_main_account_reward_claims')
    )
    op.create_index('ix_main_account_reward_claims_updated_at', 'main_account_reward_claims', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('last_main_account_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # 既存ユーザーが受け取り済みの1回限りの報酬を、メインアカウント単位で記録しておく
    # (同じメインアカウントで作った新規アカウントで再度受け取れないようにする)
    op.execute("""
        INSERT INTO main_account_reward_claims (main_account, reward_key, period, count, updated_at)
        SELECT u.main_account, 'tutorial:' || t.key, 'once', 1, now()
        FROM users u
        CROSS JOIN LATERAL jsonb_each(u.tutorial_missions) AS t(key, value)
        WHERE t.value = 'true'::jsonb
          AND t.key IN (
              'view_main_profile', 'bookmark_player', 'use_pick_tool', 'generate_profile_image',
              'view_brawler_guide', 'view_boards', 'spend_tokens'
          )
        GROUP BY u.main_account, t.key
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO main_account_reward_claims (main_account, reward_key, period, count, updated_at)
        SELECT main_account, 'app_login:ios', 'once', 1, now()
        FROM users WHERE is_ios_app_login_cleared
        GROUP BY main_account
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO main_account_reward_claims (main_account, reward_key, period, count, updated_at)
        SELECT main_account, 'app_login:android', 'once', 1, now()
        FROM users WHERE is_android_app_login_cleared
        GROUP BY main_account
        ON CONFLICT DO NOTHING
    """)
    # 利用期限内のギフトコード(トークン等に換えられる特典・応募口数)の使用回数を、メインアカウント単位で集計しておく
    op.execute("""
        INSERT INTO main_account_reward_claims (main_account, reward_key, period, count, updated_at)
        SELECT u.main_account, 'giftcode:' || g.code, 'once', count(*), now()
        FROM gift_codes g
        CROSS JOIN LATERAL jsonb_array_elements_text(g.usage_log) AS l(user_id)
        JOIN users u ON u.id = l.user_id::int
        WHERE g.usage_limit_per_user IS NOT NULL
          AND (g.expiration_datetime IS NULL OR g.expiration_datetime > now())
          AND g.reward ?| array['claim_tokens', 'claim_tickets', 'claim_elixirs', 'giveaway']
        GROUP BY u.main_account, g.code
        ON CONFLICT DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_main_account_changed_at')
    op.drop_index('ix_main_account_reward_claims_updated_at', table_name='main_account_reward_claims')
    op.drop_table('main_account_reward_claims')
    # ### end Alembic commands ###
