"""Create initial recruitment board tables

Revision ID: d581d4a82eaa
Revises: 
Create Date: 2025-07-19 07:07:44.367459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd581d4a82eaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('host_player_tag', sa.Text(), nullable=True),
    sa.Column('host_club_tag', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('conditions_application_type', sa.Text(), server_default='and', nullable=False),
    sa.Column('chat_permission_level', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('permitted_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('prohibited_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('required_highest_trophies', sa.Integer(), nullable=True),
    sa.Column('required_current_trophies', sa.Integer(), nullable=True),
    sa.Column('required_ranked_highest_rank', sa.Integer(), nullable=True),
    sa.Column('required_ranked_current_rank', sa.Integer(), nullable=True),
    sa.Column('required_ranked_highest_score', sa.Integer(), nullable=True),
    sa.Column('required_ranked_current_score', sa.Integer(), nullable=True),
    sa.Column('required_solo_pl_rank', sa.Integer(), nullable=True),
    sa.Column('required_max_power_brawlers', sa.Integer(), nullable=True),
    sa.Column('required_prestige', sa.Integer(), nullable=True),
    sa.Column('other_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['host_club_tag'], ['clubs.tag'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_player_tag'], ['players.tag'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_type_created_at_desc', 'posts', ['type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_posts_is_deleted'), 'posts', ['is_deleted'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_is_checked_created_at_desc', 'reports', ['is_checked', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_type', sa.Text(), server_default='message', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_thread_id_created_at_asc', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='_message_user_emoji_uc')
    )
    op.create_index(op.f('ix_reactions_message_id'), 'reactions', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_message_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index('idx_messages_thread_id_created_at_asc', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_reports_is_checked_created_at_desc', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_posts_is_deleted'), table_name='posts')
    op.drop_index('idx_posts_type_created_at_desc', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
