"""Add battle_log_limit to players table

Revision ID: e6986227ea29
Revises: 0865fccfe34c
Create Date: 2025-10-03 22:20:02.040413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6986227ea29'
down_revision: Union[str, Sequence[str], None] = '0865fccfe34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('battle_log_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'battle_log_limit')
    # ### end Alembic commands ###
