"""Add lower name index to players

Revision ID: f0131ce40c0f
Revises: 75d05742b70d
Create Date: 2026-03-11 09:22:00.765928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0131ce40c0f'
down_revision: Union[str, Sequence[str], None] = '75d05742b70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_index('idx_players_lower_name', 'players', [sa.text("lower(name)")], unique=False, postgresql_concurrently=True)
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.get_context().autocommit_block():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index('idx_players_lower_name', table_name='players', postgresql_concurrently=True)
        # ### end Alembic commands ###
