"""add new column to players and player_logs

Revision ID: f49acb4e4ca1
Revises: 8d5d4f296310
Create Date: 2026-06-14 17:57:10.681258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49acb4e4ca1'
down_revision: Union[str, Sequence[str], None] = '8d5d4f296310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_logs', sa.Column('ranked_season_highest_score', sa.Integer(), server_default='0', nullable=True))
    op.add_column('player_logs', sa.Column('acc_ranked_season_highest_rank', sa.Integer(), server_default='0', nullable=True))
    op.add_column('players', sa.Column('ranked_season_highest_score', sa.Integer(), server_default='0', nullable=True))
    op.add_column('players', sa.Column('acc_ranked_season_highest_rank', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'acc_ranked_season_highest_rank')
    op.drop_column('players', 'ranked_season_highest_score')
    op.drop_column('player_logs', 'acc_ranked_season_highest_rank')
    op.drop_column('player_logs', 'ranked_season_highest_score')
    # ### end Alembic commands ###
