"""Add final optimized query indexes

Revision ID: fde5caada801
Revises: 129bf868e740
Create Date: 2025-08-11 08:08:20.622233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde5caada801'
down_revision: Union[str, Sequence[str], None] = '129bf868e740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_brawler_mode_rank_date', 'ranked_stats_brawler', ['mode', 'rank_tier', 'date'], unique=False)
    op.create_index('idx_composition_mode_rank_date', 'ranked_stats_composition', ['mode', 'rank_tier', 'date'], unique=False)
    op.create_index('idx_synergy_mode_rank_date', 'ranked_stats_synergy', ['mode', 'rank_tier', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synergy_mode_rank_date', table_name='ranked_stats_synergy')
    op.drop_index('idx_composition_mode_rank_date', table_name='ranked_stats_composition')
    op.drop_index('idx_brawler_mode_rank_date', table_name='ranked_stats_brawler')
    # ### end Alembic commands ###
